[project]
name = "prog3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pandas>=2.3.0",
    "scikit-learn==1.6.1",
]
